changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: CI And Tooling
      labels:
        - ci
        - dependencies
    - title: Other Changes
      labels:
        - "*"
