CREATE TABLE IF NOT EXISTS agentmesh_uat_cases (
    case_id TEXT PRIMARY KEY,
    suite TEXT NOT NULL CHECK (suite IN ('smoke', 'unit', 'validation', 'uat')),
    component TEXT NOT NULL,
    category TEXT NOT NULL,
    test_type TEXT NOT NULL,
    execution_layer TEXT NOT NULL CHECK (
        execution_layer IN ('streamlit', 'api', 'worker', 'postgres', 'docker', 'langsmith')
    ),
    command_hint TEXT NOT NULL,
    streamlit_surface TEXT NOT NULL DEFAULT '',
    expected TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('P0', 'P1', 'P2')),
    langsmith_eval BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agentmesh_uat_cases_suite_priority
    ON agentmesh_uat_cases (suite, priority, case_id)
    WHERE active = TRUE;

CREATE INDEX IF NOT EXISTS idx_agentmesh_uat_cases_execution_layer
    ON agentmesh_uat_cases (execution_layer, component)
    WHERE active = TRUE;

INSERT INTO agentmesh_uat_cases (
    case_id,
    suite,
    component,
    category,
    test_type,
    execution_layer,
    command_hint,
    streamlit_surface,
    expected,
    priority,
    langsmith_eval,
    active,
    metadata
) VALUES
    (
        'docker.compose.config',
        'smoke',
        'docker',
        'startup',
        'configuration',
        'docker',
        'docker compose --env-file .env -f deployment/docker/compose.yml --profile combined config --quiet',
        '',
        'Compose renders without validation errors for the combined profile.',
        'P0',
        FALSE,
        TRUE,
        '{"profiles":["combined"],"fresh_environment":true}'::jsonb
    ),
    (
        'docker.compose.build',
        'smoke',
        'docker',
        'startup',
        'build',
        'docker',
        'docker compose --env-file .env -f deployment/docker/compose.yml --profile combined up -d --build',
        '',
        'Images build from a pruned Docker cache and services reach health gates.',
        'P0',
        FALSE,
        TRUE,
        '{"requires_fresh_images":true,"requires_fresh_volumes":true}'::jsonb
    ),
    (
        'streamlit.registry.dashboard',
        'uat',
        'streamlit',
        'thin-client',
        'behavior',
        'streamlit',
        'Open Streamlit Registry page and read /registry/resources plus /registry/audit-events through HTTP.',
        'Registry',
        'The UI renders resource and audit tables without direct database access.',
        'P0',
        FALSE,
        TRUE,
        '{"api_routes":["/registry/resources","/registry/audit-events"],"forbid":["DATABASE_URL","psycopg"]}'::jsonb
    ),
    (
        'streamlit.agent.direct.invoke',
        'uat',
        'agent-playground',
        'direct-flow',
        'behavior',
        'streamlit',
        'Use Agent Playground direct mode against a ready worker card.',
        'Agent Playground',
        'Direct invoke returns a final reply or an approval interrupt that can be resumed.',
        'P0',
        TRUE,
        TRUE,
        '{"api_routes":["/invoke","/conversations/{thread_id}/resume"]}'::jsonb
    ),
    (
        'streamlit.agent.control_plane.assignment',
        'uat',
        'agent-playground',
        'durable-direct-flow',
        'behavior',
        'streamlit',
        'Use Agent Playground control-plane mode to submit a durable worker assignment.',
        'Agent Playground',
        'The UI queues a workflow id and renders live activity from the control plane.',
        'P0',
        TRUE,
        TRUE,
        '{"api_routes":["/workers/{agent_id}/assignments","/workflows/{workflow_id}/activity"]}'::jsonb
    ),
    (
        'streamlit.workflow.orchestration',
        'uat',
        'workflow-playground',
        'orchestration',
        'behavior',
        'streamlit',
        'Start a workflow from Workflow Playground with preferred agents.',
        'Workflow Playground',
        'The UI renders proposed plan, live event flow, pending approvals, and terminal result.',
        'P0',
        TRUE,
        TRUE,
        '{"api_routes":["/workflows/start","/workflows/{workflow_id}/approvals","/workflows/{workflow_id}/activity"]}'::jsonb
    ),
    (
        'streamlit.workflow.open_existing',
        'uat',
        'workflow-playground',
        'workflow-lookup',
        'behavior',
        'streamlit',
        'Open an existing workflow id in Workflow Playground.',
        'Workflow Playground',
        'The opened workflow keeps independent session state from the active orchestration workflow.',
        'P1',
        FALSE,
        TRUE,
        '{"session_keys":["active_orchestration_workflow_id","opened_workflow_id"]}'::jsonb
    ),
    (
        'streamlit.workflow.checkpoints',
        'uat',
        'workflow-playground',
        'checkpointing',
        'behavior',
        'streamlit',
        'Use checkpoint controls: load checkpoints, inspect selected, recover selected, rerun workflow, rerun task.',
        'Workflow Playground',
        'Checkpoint replay is read-only; recovery and reruns create new workflow ids and reset UI activity state.',
        'P0',
        TRUE,
        TRUE,
        '{"api_routes":["/workflows/{workflow_id}/checkpoints","/workflows/{workflow_id}/replay","/workflows/{workflow_id}/recover","/workflows/{workflow_id}/rerun","/workflows/{workflow_id}/tasks/{task_id}/rerun"]}'::jsonb
    ),
    (
        'streamlit.workflow.operations_layout',
        'uat',
        'workflow-playground',
        'responsive-layout',
        'behavior',
        'streamlit',
        'Open a persisted workflow and inspect the workflow activity layout on desktop and narrow viewports.',
        'Workflow Playground',
        'Recovery controls, plan and result, and live event trail render as left, center, and right thirds on desktop and stack without overlap on narrow screens.',
        'P1',
        FALSE,
        TRUE,
        '{"desktop_columns":["checkpoints","workspace","events"],"mobile_behavior":"stack","browser_validation":true}'::jsonb
    ),
    (
        'streamlit.workflow.event_trail',
        'uat',
        'workflow-playground',
        'event-visualization',
        'behavior',
        'streamlit',
        'Open a persisted workflow with multiple events and inspect the live event trail and output controls.',
        'Workflow Playground',
        'Events appear newest first as numbered linked timeline nodes with event name, source to destination route, and a control that displays the complete event output.',
        'P0',
        FALSE,
        TRUE,
        '{"ordering":"sequence_number_desc","visible_number":"sequence_number","fields":["event_type","source_agent","target_agent"],"output":"complete_event_json"}'::jsonb
    ),
    (
        'streamlit.navigation.top_pages',
        'uat',
        'streamlit',
        'navigation',
        'behavior',
        'streamlit',
        'Switch between Registry, Agent Playground, and Workflow Playground using the top page buttons.',
        'All pages',
        'Top navigation changes pages while preserving each page session state and no sidebar navigation is rendered.',
        'P1',
        FALSE,
        TRUE,
        '{"pages":["Registry","Agent Playground","Workflow Playground"],"placement":"top"}'::jsonb
    ),
    (
        'streamlit.registry.connect_url',
        'uat',
        'streamlit',
        'registry-connection',
        'behavior',
        'streamlit',
        'On the Registry page, enter a registry base URL and select Connect, then use Disconnect.',
        'Registry',
        'The configured URL is prefilled but inactive; Connect health-checks the target and Disconnect clears registry-bound session state.',
        'P0',
        FALSE,
        TRUE,
        '{"prefill":"AGENTMESH_API_URL","auto_connect":false,"disconnect":true,"health_route":"/health","scope":"browser_session"}'::jsonb
    ),
    (
        'api.workflow.approval_gates',
        'smoke',
        'workflow',
        'runtime',
        'integration',
        'api',
        'POST /workflows/start and approve pending workflow gates.',
        'Workflow Playground',
        'The workflow passes plan approval, agent output approval, and completion with workflow.result.',
        'P0',
        TRUE,
        TRUE,
        '{"required_events":["PLAN_APPROVAL_REQUESTED","PLAN_APPROVED","AGENT_APPROVAL_REQUESTED","WORKFLOW_COMPLETED"]}'::jsonb
    ),
    (
        'api.worker.retry.transient_failure',
        'validation',
        'workers',
        'retry',
        'failure-handling',
        'api',
        'Submit a transient worker failure such as 429, timeout, or 502-504 to the worker result route.',
        'Workflow Playground',
        'The control plane schedules retry state without waking or perturbing the supervisor.',
        'P0',
        FALSE,
        TRUE,
        '{"transient_statuses":[429,502,503,504],"owner":"control-plane"}'::jsonb
    ),
    (
        'api.worker.semantic_failure.replan',
        'validation',
        'supervisor',
        'replan',
        'failure-handling',
        'api',
        'Submit a semantic worker failure and inspect supervisor action queue.',
        'Workflow Playground',
        'Semantic failure creates checkpoint review or replan work and keeps historical plan versions immutable.',
        'P0',
        TRUE,
        TRUE,
        '{"owner":"supervisor","immutability":["workflow_id","plan_version","step_id"]}'::jsonb
    ),
    (
        'api.workflow.activity.pagination',
        'unit',
        'workflow',
        'projection',
        'api-contract',
        'api',
        'GET /workflows/{workflow_id}/activity?after_sequence=...&limit=...',
        'Workflow Playground',
        'Activity pagination returns monotonic event cursors, projected steps, pending interrupts, and terminal flag.',
        'P0',
        FALSE,
        TRUE,
        '{"cursor":"next_sequence","max_limit":500}'::jsonb
    ),
    (
        'postgres.workflow_events.persisted',
        'validation',
        'postgres',
        'persistence',
        'database-contract',
        'postgres',
        'SELECT event_type FROM agentmesh_events WHERE workflow_id = ... ORDER BY sequence_number',
        '',
        'Durable events exist in deterministic workflow order after live smoke checks.',
        'P0',
        FALSE,
        TRUE,
        '{"table":"agentmesh_events","ordering":"sequence_number"}'::jsonb
    ),
    (
        'postgres.claims.retry_deadletter',
        'validation',
        'postgres',
        'queueing',
        'database-contract',
        'postgres',
        'Inspect agentmesh_event_claims after retries and failures.',
        '',
        'Leases, retry counters, next-at timestamps, and dead-letter markers are durable in PostgreSQL.',
        'P0',
        FALSE,
        TRUE,
        '{"table":"agentmesh_event_claims","owner":"control-plane"}'::jsonb
    ),
    (
        'postgres.checkpoint.mapping',
        'validation',
        'postgres',
        'checkpointing',
        'database-contract',
        'postgres',
        'Inspect workflow checkpoints and LangGraph checkpoint mappings for a completed workflow.',
        'Workflow Playground',
        'Checkpoint ids are mapped to workflow event cursors and can be replayed or recovered deterministically.',
        'P0',
        FALSE,
        TRUE,
        '{"routes":["/workflows/{workflow_id}/checkpoints","/workflows/{workflow_id}/replay","/workflows/{workflow_id}/recover"]}'::jsonb
    ),
    (
        'unit.streamlit.http_only_client',
        'unit',
        'streamlit',
        'thin-client',
        'source-contract',
        'streamlit',
        'Run tests/unit/test_streamlit_client.py.',
        'Registry, Agent Playground, Workflow Playground',
        'Streamlit talks only to HTTP APIs and never receives database credentials.',
        'P0',
        FALSE,
        TRUE,
        '{"test_file":"tests/unit/test_streamlit_client.py"}'::jsonb
    ),
    (
        'unit.worker.assignment_claims',
        'unit',
        'workers',
        'queueing',
        'source-contract',
        'worker',
        'Run tests/unit/test_event_repository.py claim and pending-assignment cases.',
        '',
        'Assignments with proposed or completed output do not re-enter pending worker queues.',
        'P0',
        FALSE,
        TRUE,
        '{"test_file":"tests/unit/test_event_repository.py"}'::jsonb
    ),
    (
        'unit.task_output.validation',
        'unit',
        'validation',
        'deterministic-validation',
        'source-contract',
        'api',
        'Run tests/unit/test_task_output_validation.py.',
        '',
        'Task output validation is deterministic and routes semantic failures to supervisor review.',
        'P0',
        FALSE,
        TRUE,
        '{"test_file":"tests/unit/test_task_output_validation.py"}'::jsonb
    ),
    (
        'unit.checkpoint.replay_contract',
        'unit',
        'checkpointing',
        'replay',
        'source-contract',
        'api',
        'Run checkpoint replay/recover/rerun API contract tests.',
        'Workflow Playground',
        'Replay is read-only while recover, workflow rerun, and task rerun return fresh workflow identifiers.',
        'P0',
        FALSE,
        TRUE,
        '{"routes":["/replay","/recover","/rerun","/tasks/{task_id}/rerun"]}'::jsonb
    ),
    (
        'langsmith.project_auth',
        'smoke',
        'langsmith',
        'observability',
        'external-contract',
        'langsmith',
        'LangSmith Client lists configured project and recent runs.',
        '',
        'Configured project is reachable and recent AgentMesh-shaped traces are visible.',
        'P0',
        TRUE,
        TRUE,
        '{"requires_env":["LANGSMITH_API_KEY","LANGSMITH_PROJECT"]}'::jsonb
    ),
    (
        'langsmith.traces.clear_before_uat',
        'validation',
        'langsmith',
        'observability',
        'external-contract',
        'langsmith',
        'Delete or recreate the configured LangSmith project before fresh UAT trace collection.',
        '',
        'Fresh UAT runs are not mixed with stale trace samples from previous builds.',
        'P1',
        FALSE,
        TRUE,
        '{"destructive":true,"requires_env":["LANGSMITH_API_KEY","LANGSMITH_PROJECT"]}'::jsonb
    ),
    (
        'logs.no_runtime_errors',
        'validation',
        'observability',
        'runtime',
        'log-scan',
        'docker',
        'Scan docker logs after smoke and UAT flows.',
        '',
        'Runtime logs contain no unexpected fatal errors, auth failures, refused connections, or tracebacks.',
        'P1',
        FALSE,
        TRUE,
        '{"known_transient_patterns":["rate_limit_exceeded","429 Too Many Requests"]}'::jsonb
    )
ON CONFLICT (case_id) DO UPDATE SET
    suite = EXCLUDED.suite,
    component = EXCLUDED.component,
    category = EXCLUDED.category,
    test_type = EXCLUDED.test_type,
    execution_layer = EXCLUDED.execution_layer,
    command_hint = EXCLUDED.command_hint,
    streamlit_surface = EXCLUDED.streamlit_surface,
    expected = EXCLUDED.expected,
    priority = EXCLUDED.priority,
    langsmith_eval = EXCLUDED.langsmith_eval,
    active = EXCLUDED.active,
    metadata = EXCLUDED.metadata,
    updated_at = CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW v_agentmesh_uat_case_summary AS
SELECT suite, execution_layer, priority, COUNT(*) AS case_count
FROM agentmesh_uat_cases
WHERE active = TRUE
GROUP BY suite, execution_layer, priority;

CREATE OR REPLACE VIEW v_agentmesh_langsmith_eval_cases AS
SELECT *
FROM agentmesh_uat_cases
WHERE active = TRUE AND langsmith_eval = TRUE;
