"""Canonical event type registry for AgentMesh.

All valid event_type strings must be declared here. The Event model
validator rejects any string not present in VALID_EVENT_TYPES.
"""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    """Canonical event types used by the AgentMesh event log."""

    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"
    WORKFLOW_RERUN_REQUESTED = "WORKFLOW_RERUN_REQUESTED"
    TASK_RERUN_REQUESTED = "TASK_RERUN_REQUESTED"
    AGENT_SNAPSHOT_CAPTURED = "AGENT_SNAPSHOT_CAPTURED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_APPROVAL_REQUESTED = "PLAN_APPROVAL_REQUESTED"
    PLAN_APPROVED = "PLAN_APPROVED"
    PLAN_REVISION_REQUESTED = "PLAN_REVISION_REQUESTED"
    PLAN_REJECTED = "PLAN_REJECTED"
    TASK_PROPOSED = "TASK_PROPOSED"
    TASK_APPROVAL_REQUESTED = "TASK_APPROVAL_REQUESTED"
    TASK_APPROVED = "TASK_APPROVED"
    TASK_REVISION_REQUESTED = "TASK_REVISION_REQUESTED"
    TASK_REJECTED = "TASK_REJECTED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    AGENT_OUTPUT_PROPOSED = "AGENT_OUTPUT_PROPOSED"
    AGENT_APPROVAL_REQUESTED = "AGENT_APPROVAL_REQUESTED"
    AGENT_OUTPUT_APPROVED = "AGENT_OUTPUT_APPROVED"
    AGENT_OUTPUT_REVISION_REQUESTED = "AGENT_OUTPUT_REVISION_REQUESTED"
    AGENT_OUTPUT_REJECTED = "AGENT_OUTPUT_REJECTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    JOB_DETECTED = "JOB_DETECTED"
    EMAIL_FOUND = "EMAIL_FOUND"
    APPLICATION_SENT = "APPLICATION_SENT"
    AGENT_STATUS = "AGENT_STATUS"


VALID_EVENT_TYPES: frozenset[str] = frozenset(event_type.value for event_type in EventType)
REGISTERED_EVENT_TYPES: tuple[str, ...] = tuple(sorted(VALID_EVENT_TYPES))
